---
title: "Section 2"
author: "Ana Martinovici"
date: "Last compiled on `r Sys.time()`"
output: 
    bookdown::html_document2:
        css: '..\style.css'
        toc: true
        toc_float: 
            collapsed: false
        number_sections: true
        code_folding: show
        theme: cerulean
editor_options: 
  chunk_output_type: console
---

```{r setup-section2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

4. How to include code from external scripts

This example shows how to print specific lines from an external script. You can use this to show, in your final report, what specific queries you've used, how you requested data from the API, and other relevant steps in your project.
  
```{r, inc-query} 
file_name <- here::here("examples", "recent_search", "collect_data.R") 
start_line <- 92
end_line <- 99 
knitr::read_chunk(path = file_name, labels = "my-query-params", from = start_line, to = end_line) 
 
file_in_repo <- stringr::str_sub(file_name, start = stringr::str_locate(file_name, "/ADF_public")[1, "start"]) 
  
``` 
  
 Specifically, we are including lines `r start_line`:`r end_line` from `r file_in_repo`: 

```{r, my-query-params, eval = FALSE, echo = TRUE} 
``` 


